/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/3dNHKpvS8bV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"
import { Slider } from "@/components/ui/slider"
import { Button } from "@/components/ui/button"
import poppins from "@/font/font"
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import { useRouter } from "next/navigation"

export default function Docs() {
    const router = useRouter();
  return (
    <div className={`${poppins.className}`}>
        <Header />

        <section className="bg-gray-200 py-4 md:py-20 flex flex-col md:flex-row items-center justify-center md:gap-6 xl:gap-16 px-2">
        {/* This DIV will be used to write the slogan */}
        <div className="text-center py-2">
          <h1 className="text-2xl md:text-5xl xl:text-7xl 2xl:text-7xl font-bold text-[#16302B] mb-4 xl:mb-10 2xl:mb-10">
            <span>Get started with </span>
            <button className="xl:py-1 2xl:py-1 px-1 xl:px-4 2xl:px-4 border border-blue-200 border-opacity-20 bg-[#397367] text-white rounded-xl">
              Scail
            </button>
          </h1>
          <h2 className="px-4 xl:px-0 2xl:px-0 text-xs xl:text-xl 2xl:text-xl text-[#000000]">
            We provide you video with audio simulation of the product to help you understand the product better.
          </h2>
        </div>
        <div>
            <img src="/svgs/10.png" alt="10" className="h-28 w-28 md:h-40 md:w-40 xl:h-48 xl:w-48"/>
        </div>
      </section>

    <div className={`grid md:grid-cols-[300px_1fr] gap-8 p-4 md:p-8 2xl:flex 2xl:items-center 2xl:justify-center`}>
      <div className="bg-background rounded-lg shadow-sm border border-muted/10 overflow-hidden">
        <div className="sticky top-0 bg-background py-4 border-b border-muted/10">
          <h2 className="text-xl font-semibold px-6 text-foreground">Frequently Asked Questions</h2>
        </div>
        <nav className="py-4">
          <ul className="space-y-1">
            <li>
              <button className="flex items-center justify-between w-full px-6 py-3 text-left hover:bg-muted/10 focus:bg-muted/10 focus:outline-none rounded-md transition-colors">
                <span className="text-foreground">What is this product?</span>
                <ChevronRightIcon className="w-4 h-4 text-muted-foreground" />
              </button>
            </li>
            <li>
              <button className="flex items-center justify-between w-full px-6 py-3 text-left hover:bg-muted/10 focus:bg-muted/10 focus:outline-none rounded-md transition-colors">
                <span className="text-foreground">How does it work?</span>
                <ChevronRightIcon className="w-4 h-4 text-muted-foreground" />
              </button>
            </li>
            <li>
              <button className="flex items-center justify-between w-full px-6 py-3 text-left hover:bg-muted/10 focus:bg-muted/10 focus:outline-none rounded-md transition-colors">
                <span className="text-foreground">What are the key features?</span>
                <ChevronRightIcon className="w-4 h-4 text-muted-foreground" />
              </button>
            </li>
            <li>
              <button className="flex items-center justify-between w-full px-6 py-3 text-left hover:bg-muted/10 focus:bg-muted/10 focus:outline-none rounded-md transition-colors">
                <span className="text-foreground">How do I get started?</span>
                <ChevronRightIcon className="w-4 h-4 text-muted-foreground" />
              </button>
            </li>
            <li>
              <button className="flex items-center justify-between w-full px-6 py-3 text-left hover:bg-muted/10 focus:bg-muted/10 focus:outline-none rounded-md transition-colors">
                <span className="text-foreground">What are the pricing options?</span>
                <ChevronRightIcon className="w-4 h-4 text-muted-foreground" />
              </button>
            </li>
            <li>
              <button className="flex items-center justify-between w-full px-6 py-3 text-left hover:bg-muted/10 focus:bg-muted/10 focus:outline-none rounded-md transition-colors">
                <span className="text-foreground">Where can I find support?</span>
                <ChevronRightIcon className="w-4 h-4 text-muted-foreground" />
              </button>
            </li>
          </ul>
        </nav>
      </div>
      <div className="bg-background rounded-lg shadow-sm border border-muted/10 overflow-hidden">
        <div className="sticky top-0 bg-background py-4 border-b border-muted/10">
          <h2 className="text-xl font-semibold px-6 text-foreground">Video Responses</h2>
        </div>
        <div className="p-6">
          <div className="relative w-full max-w-2xl overflow-hidden rounded-lg aspect-video"           >
            <video className="w-full">
              <source
                src="https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4"
                type="video/mp4"
              />
            </video>
            <div className="absolute inset-x-0 bottom-0 grid gap-2 bg-gradient-to-b from-transparent to-black/50">
              <div className="px-2">
                <Slider
                  className="w-full [&>span:first-child]:h-1 [&>span:first-child]:bg-white/30 [&_[role=slider]]:bg-red-500 [&_[role=slider]]:w-3 [&_[role=slider]]:h-3 [&_[role=slider]]:border-0 [&>span:first-child_span]:bg-red-500 [&_[role=slider]:focus-visible]:ring-0 [&_[role=slider]:focus-visible]:ring-offset-0 [&_[role=slider]:focus-visible]:scale-105 [&_[role=slider]:focus-visible]:transition-transform"
                  defaultValue={[40]}
                />
              </div>
              <div className="flex items-center gap-3 p-3 pt-0 text-white [&_svg]:text-white">
                <Button size="icon" variant="ghost" className="w-9 h-9 hover:bg-black/50 rounded-full"
                      onClick={() => {
                        router.push("/503")
                      }}>
                  <PlayIcon className="w-6 h-6 fill-white" />
                </Button>
                <Button size="icon" variant="ghost" className="w-9 h-9 hover:bg-black/50 rounded-full">
                  <SkipForwardIcon className="w-6 h-6 fill-white" />
                </Button>
                <Button size="icon" variant="ghost" className="w-9 h-9 hover:bg-black/50 rounded-full">
                  <Volume2Icon className="w-6 h-6 fill-white" />
                </Button>
                <div className="text-sm">1:20 / 3:45</div>
                <Button size="icon" variant="ghost" className="ml-auto w-9 h-9 hover:bg-black/50 rounded-full">
                  <MaximizeIcon className="w-6 h-6" />
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <Footer />
    </div>
  )
}

function ChevronRightIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function MaximizeIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 3H5a2 2 0 0 0-2 2v3" />
      <path d="M21 8V5a2 2 0 0 0-2-2h-3" />
      <path d="M3 16v3a2 2 0 0 0 2 2h3" />
      <path d="M16 21h3a2 2 0 0 0 2-2v-3" />
    </svg>
  )
}


function PlayIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="6 3 20 12 6 21 6 3" />
    </svg>
  )
}


function SkipForwardIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="5 4 15 12 5 20 5 4" />
      <line x1="19" x2="19" y1="5" y2="19" />
    </svg>
  )
}


function Volume2Icon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5" />
      <path d="M15.54 8.46a5 5 0 0 1 0 7.07" />
      <path d="M19.07 4.93a10 10 0 0 1 0 14.14" />
    </svg>
  )
}
