/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vwMALWrD9Ly
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Loading() {
  //text-xl font-italic text-center mt-10
  return (
    <div className="flex flex-col items-center justify-center mt-10">
      <div className="animate-spin rounded-full h-12 w-12 border-4 border-gray-500 border-t-transparent mt-80" >      </div>
      <p className="mt-4 text-gray-500 dark:text-gray-400">Loading...</p>

    </div>
  )
}
