/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qSj4C8jvLvu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, Avatar } from "@/components/ui/avatar"
import { Switch } from "@/components/ui/switch"
import { CardHeader, CardContent, Card } from "@/components/ui/card"

export function Component() {
  return (
    <div className="grid min-h-[400px] gap-6 lg:grid-cols-2">
      <div className="grid gap-4 p-4 lg:gap-6 xl:gap-8">
        <div className="flex items-center space-x-4">
          <Avatar className="w-10 h-10">
            <AvatarImage alt="Avatar" src="/avatar.jpg" />
            <div>AD</div>
          </Avatar>
          <div className="flex-1">
            <h3 className="text-lg font-bold">Alice Davis</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">Sales Manager</p>
          </div>
          <Switch defaultChecked id="user-1" />
        </div>
        <div className="flex items-center space-x-4">
          <Avatar className="w-10 h-10">
            <AvatarImage alt="Avatar" src="/avatar.jpg" />
            <div>AD</div>
          </Avatar>
          <div className="flex-1">
            <h3 className="text-lg font-bold">Bob Harris</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">Product Manager</p>
          </div>
          <Switch id="user-2" />
        </div>
        <div className="flex items-center space-x-4">
          <Avatar className="w-10 h-10">
            <AvatarImage alt="Avatar" src="/avatar.jpg" />
            <div>AD</div>
          </Avatar>
          <div className="flex-1">
            <h3 className="text-lg font-bold">Ella Turner</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">Software Engineer</p>
          </div>
          <Switch defaultChecked id="user-3" />
        </div>
        <div className="flex items-center space-x-4">
          <Avatar className="w-10 h-10">
            <AvatarImage alt="Avatar" src="/avatar.jpg" />
            <div>AD</div>
          </Avatar>
          <div className="flex-1">
            <h3 className="text-lg font-bold">Oscar King</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">UX Designer</p>
          </div>
          <Switch id="user-4" />
        </div>
        <div className="flex items-center space-x-4">
          <Avatar className="w-10 h-10">
            <AvatarImage alt="Avatar" src="/avatar.jpg" />
            <div>AD</div>
          </Avatar>
          <div className="flex-1">
            <h3 className="text-lg font-bold">Zoe Wright</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">Data Analyst</p>
          </div>
          <Switch id="user-5" />
        </div>
      </div>
      <div className="grid gap-4 p-4 lg:gap-6 xl:gap-8">
        <Card>
          <CardHeader className="p-4">
            <div className="text-lg font-bold">Map</div>
          </CardHeader>
          <CardContent className="p-4">
            <div className="h-[300px] rounded-lg border" />
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
